
spring:
  application:
   name: data-generator
  datasource:
    url: jdbc:postgresql://192.168.0.189/factory
    username: mermer
    password: mermer
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
server:
  port: 8083

